-- Add columns required by app/api/power-calculations/route.ts
-- Safe to run repeatedly on MariaDB/MySQL versions that support IF NOT EXISTS.

ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS pre_inst_id INT(11) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS usage_history LONGTEXT NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS voltage DECIMAL(10,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS current DECIMAL(10,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS power_factor DECIMAL(5,4) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS phase_type VARCHAR(20) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS company_name VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS product_price DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS avg_monthly_usage DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS power_saving_rate DECIMAL(5,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS unit_price DECIMAL(10,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS expected_savings_percent DECIMAL(5,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS device_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS amortize_months INT(11) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS payment_months INT(11) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS contracted_capacity DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS peak_power DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS device_capacity DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS faucet_method VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS usage_data_months INT(11) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS emission_factor DECIMAL(10,6) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS appliances LONGTEXT NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS monthly_kwh LONGTEXT NULL DEFAULT NULL;

ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS january_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS january_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS february_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS february_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS march_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS march_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS april_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS april_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS may_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS may_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS june_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS june_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS july_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS july_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS august_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS august_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS september_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS september_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS october_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS october_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS november_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS november_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS december_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS december_cost DECIMAL(15,2) NULL DEFAULT NULL;

ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS total_annual_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS total_annual_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS average_monthly_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS average_monthly_cost DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS roi_years DECIMAL(10,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS roi_months DECIMAL(10,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS annual_savings_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS annual_savings_baht DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS monthly_savings_kwh DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS monthly_savings_baht DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS monthly_payment DECIMAL(15,2) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS carbon_reduction DECIMAL(15,4) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS breakeven_year INT(11) NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS cumulative_10year_savings DECIMAL(15,2) NULL DEFAULT NULL;

ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS twelve_months LONGTEXT NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS pre_install_results LONGTEXT NULL DEFAULT NULL;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS show_12month_modal TINYINT(1) NULL DEFAULT 0;
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS status VARCHAR(20) NULL DEFAULT 'completed';
ALTER TABLE power_calculations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

UPDATE power_calculations SET status = 'completed' WHERE status IS NULL;
